version: "3.7"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - .env
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "${PMA_LISTEN:-36001}:80"
    networks:
      comely-app-net:
        ipv4_address: 10.0.20.10
networks:
    comely-app-net:
      driver: bridge
      ipam:
        config:
        - subnet: 10.0.20.9/27
